### ISSUE TITLE
Error en modificarCliente en Setter y Getter

### ISSUE THREAD

**Issue by SoyFefoo** [claudio1697/DamGym#3]

**Comment by claudio1697** [comment]
Creo que es de tu portatil o de tu intellij, quiza sea la version de java, yo uso la 17

**Comment by llllllllll2** [comment]
@Getter/Setter a veces explota
Mejor escribirlo completo;
 public Long getId_Cliente() {
        return id_clase;
    }

    public void setId_clase(Long id_Cliente) {
        this.id_clase = id_clase;
    }
